fpl_name_map = {
    "GW Gameweek": "gameweek",
    "Pts": "points",
    "MPMinutes played": "minutes_played",
    "GSGoals scored": "goals_scored",
    "AAssists": "assists",
    "CSClean sheets": "clean_sheets",
    "GCGoals conceded": "goals_conceded",
    "OGOwn goals": "own_goals",
    "PSPenalties saved": "penalties_saved",
    "PMPenalties missed": "penalties_missed",
    "YCYellow cards": "yellow_cards",
    "RCRed cards": "red_cards",
    "SSaves": "saves",
    "BBonus": "bonus",
    "BPSBonus Points System": "bonus_points_system",
    "IInfluence": "influence",
    "CCreativity": "creativity",
    "TThreat": "threat",
    "IIICT Index": "ict_index",
    "NT Net Transfers": "net_transfers",
    "SB Selected by": "selected_by",
    "£ Value": "value",
    "Name": "name",
    "Team": "team",
    "Position": "position",
}
"""
Dictionary used to rename features scraped from FPL website
"""
