STATIC_FEATURES = [
    'was_home',
    'gw',
    'promoted_side',
    'top_6_last_season',
    'ID',
    'position_DEF',
    'position_FWD',
    'position_GK',
    'position_MID',
    'promoted_side_opponent', 'top_6_last_season_opponent',
    'kickoff_month_Apr', 'kickoff_month_Aug', 'kickoff_month_Dec', 'kickoff_month_Feb', 'kickoff_month_Jan',
    'kickoff_month_Mar', 'kickoff_month_May', 'kickoff_month_Nov', 'kickoff_month_Oct', 'kickoff_month_Sep',
    'late_kickoff',
    'early_kickoff'
]

TIME_SERIES_FEATURES = [
    'assists',
    'bonus',
    'target_missed',
    'errors_leading_to_goal_attempt',
    'creativity',
    'key_passes',
    'yellow_cards',
    'loaned_in',
    'team_a_score',
    'team_h_score',
    'clearances_blocks_interceptions',
    'offside',
    'dribbles',
    'loaned_out',
    'selected',
    'big_chances_missed',
    'ict_index',
    'red_cards',
    'value',
    'fouls',
    'influence',
    'errors_leading_to_goal',
    'ea_index',
    'goals_scored',
    'tackles',
    'transfers_balance',
    'transfers_in',
    'transfers_out',
    'attempted_passes',
    'completed_passes',
    'bps',
    'penalties_missed',
    'own_goals',
    'saves',
    'penalties_saved',
    'goals_conceded',
    'open_play_crosses',
    'total_points',
    'tackled',
    'clean_sheets',
    'winning_goals',
    'minutes',
    'big_chances_created',
    'penalties_conceded',
    'recoveries',
    'threat'
]
